name: voice_recorder
description: A comprehensive audio recording package for Flutter with waveform visualization, interruption handling, and flexible configuration. Perfect for voice recording, audio notes, and podcast apps.
version: 0.1.0
homepage: https://github.com/prathviksankaliya/recorder
repository: https://github.com/prathviksankaliya/recorder
documentation: https://github.com/prathviksankaliya/recorder#readme

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.2
  audio_session: ^0.2.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Package does not include UI assets
# flutter:
#   uses-material-design: true
